generatorName: go
ignoreFileOverride: ".openapi-generator-ignore"
templateDir: "template"
gitUserId: "phoenixnap"
gitRepoId: "go-sdk-bmc"
additionalProperties:
  generateInterfaces: true
  isGoSubmodule: true
  useOneOfDiscriminatorLookup: true