name: 'Build SDK'
description: 'Build SDK for a given API'
inputs:
  module-name:
    description: 'Name of the Go module.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install golang
      shell: bash
      run: |
        sudo apt-get update 
        sudo apt-get install golang-go
    - name: Build go module
      shell: bash
      run: cd ${{ inputs.module-name }} && go version && go mod tidy && go build