name: 'Test SDK'
description: 'Test SDK using a given test file.'
runs:
  using: "composite"
  steps:
    - name: Install golang
      shell: bash
      run: sudo apt-get install golang-go
    - name: Run tests
      shell: bash
      run: |
        cd tests
        go test -v