name: 'Test SDK'
description: 'Test SDK using a given test file.'
inputs:
  test-report-dir:
    description: 'The location of the test reports'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install golang
      shell: bash
      run: sudo apt-get install golang-go
    - name: Install go-junit-report
      shell: bash
      run: |
        go get github.com/jstemmer/go-junit-report
    - name: Run tests
      shell: bash
      run: |
        cd tests
        export GOPATH="$HOME/go/"
        export PATH=$PATH:$GOPATH/bin
        go install github.com/golang/mock/mockgen@v1.6.0
        go install github.com/jstemmer/go-junit-report@latest
        go generate ./...
        go test -v ./... | go-junit-report -set-exit-code > report.xml     
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: '${{ inputs.test-report-dir }}/*' 